#!/usr/bin/env bash

REPODIR=`git rev-parse --show-toplevel`

cd "$REPODIR/models"

VERSION="0.1-test"

if [ ! -f "lv-morpho-model.ser.gz" ] || [ ! -f ".version" ] || [ `cat .version` != "$VERSION" ]; then
	echo "Downloading models..."
	curl -L -O https://github.com/PeterisP/LVTagger/releases/download/model-bin-0.1-test/lv-morpho-model.ser.gz
	echo $VERSION > .version
else
	echo "Models up-to-date"
fi

